version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx # Dockerfile location
      # args:
      #   - WP_PASSWORD=$MYSQL_PASSWORD
    ports:
      - 443:443
  # mariadb:
  #   build: ./requirements/mariadb
    # ports:
      # - 3306:3306
  # wordpress:
  #   build: ./requirements/wordpress
  #   volumes:
      # - # wordpress database volume
      # - # wordpress sourcecode volume
  
  # networks:
    