version:  '3'

services:
  mariadb:
    restart: "always"
    build: ./requirements/mariadb
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - wp-database:/var/lib/mysql/wordpress
    networks:
      - incept

  wordpress:
    restart: "always"
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    env_file:
      - ./.env
    ports:
      - 9000:9000
    volumes:
      - wp-data:/var/www/html/
    networks:
      - incept

  nginx:
    restart: "always"
    depends_on:
      - wordpress
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wp-data:/var/www/html/
    networks:
      - incept

volumes:
  wp-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/abel-haj/data/wp_files'

  wp-database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/abel-haj/data/wp_database'

networks:
  incept:
