# version: '3.8'
version: '3.3'

services:
    nginx: # service name
        restart: "always" # restart on crash
        build:
            context: ./requirements/nginx # Dockerfile location
            # args: # arguments passed to Dockerfile
            #     - WP_PASSWORD=$MYSQL_PASSWORD
        ports: # necessary ports
            - 443:443

    mariadb:
        restart: "always"
        build:
            context: ./requirements/mariadb
        environment: # pass variables from .env file to container environment
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        ports:
            - 3306:3306

#     wordpress:
#         restart: "always"
#         build:
#             context: ./requirements/wordpress
#         environment:
#             MYSQL_DATABASE: "${MYSQL_DATABASE}"
#             MYSQL_USER: "${MYSQL_USER}"
#             MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
#         ports:
#             - 9000:9000
#         volumes:
#             # - # wordpress database volume
#             # - # wordpress sourcecode volume
    
    # networks:
        # incept